site_name: 王浩雄的个人主页
site_url: https://note.haoxiong.wang
site_description: 王浩雄的个人主页
repo_name: "WangHX2024/note"
repo_url: https://github.com/WangHX2024/note
edit_uri: blob/master/docs
copyright: Copyright &copy; 2023 - 2025 WangHX. <a href="https://beian.miit.gov.cn">冀ICP备2024085995号</a>
# copyright: Copyright &copy; 2023 - 2025 WangHX.


theme:
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: 切换至夜间模式
      primary: "#448aff"
      accent: "#448aff"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
      primary: "#448aff"
      accent: "#448aff"
  font:
    text: LXGW WenKai Screen GB Screen
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    
extra:
  generator: true
  social:
    - icon: fontawesome/brands/weixin # 图标 : https://fontawesome.com
      link: /files/wechat.png
      name: 微信公众号
    - icon: fontawesome/brands/qq 
      link: https://3047901150.qzone.qq.com
      name: QQ空间
    - icon: fontawesome/brands/github 
      link: https://github.com/WangHX2024/
      name: GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/wanghx2025
      name: Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/wanghx01
      name: X
    - icon: fontawesome/solid/paper-plane
      link: mailto:<wanghaoxiong@zju.edu.cn>
      name: 电子邮件
  analytics:
    provider: google
    property: G-PLSZR8E9QE
    # feedback:
    #   title: 激励
    #   ratings:
    #     - icon: fontawesome/regular/hand-back-fist
    #       name: 激励
    #       data: 1
    #       note: >- 
    #         <center> 感谢支持</center>
            
extra_javascript:
  - css_js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - css_js/css.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  
plugins:
  - tags
  - blog:
      blog_dir: blog
      blog_toc: true
      draft: true
  - search
  - glightbox
  - statistics:
      page_check_metadata: counter
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      exclude:
  - git-committers:
      repository: wanghx2024/blog
      exclude:


markdown_extensions:
  - abbr
  - admonition
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - 主页 Home: 
    - index.md
    - 留言板: home/comment.md
    - 链接: home/link.md
  - 博客 Blog:
    - blog/index.md
  - 笔记 Note: 
    - note/index.md
    - 数字逻辑设计:
      - note/dld/index.md
      - "Chapter 1: Digital Systems and Information": note/dld/chap1/chap1.md
      - "Chapter 2: Combinational Logic Circuits": note/dld/chap2/chap2.md
      - "Chapter 3: Combinational Logic Design": note/dld/chap3/chap3.md
      - "Chapter 4: Sequential Circuits": note/dld/chap4/chap4.md
      - "Chapter 5: Hardware Implementation": note/dld/chap5/chap5.md
      - "Chapter 6: Register and Register Transfer": note/dld/chap6/chap6.md
      - "资料下载：实验报告": note/dld/file_download.md
    - 计算机体系结构:
      - note/ca/index.md
      - "Chapter 1: Fundamentals of Computer Design": note/ca/chap1/chap1.md
      - "Chapter 2: Memory Hierarchy Design": note/ca/chap2/chap2.md
      - "Chapter 3: Instruction-Level Parallelism": note/ca/chap3/chap3.md
      - "资料下载：实验报告与 A4 Cheatpaper": note/ca/file_download.md
    - 数据库系统:
      - note/db/index.md
      - "Chapter 1: Introduction": note/db/chap1/chap1.md
      - "Chapter 2: Relational Model": note/db/chap2/chap2.md
      - "Chapter 3: SQL": note/db/chap3/chap3.md
      - "Chapter 4: Advanced SQL": note/db/chap4/chap4.md
      - "Chapter 5: Entity-Relationship Model": note/db/chap5/chap5.md
      - "Chapter 6: Relational Database Design": note/db/chap6/chap6.md
      - "Chapter 7: Storage and File Structure": note/db/chap7/chap7.md
      - "Chapter 8: Indexing and Hashing": note/db/chap8/chap8.md
      - "Chapter 9: Query Processing": note/db/chap9/chap9.md
      - "Chapter 10: Query Optimization": note/db/chap10/chap10.md
      - "Chapter 11: Transactions": note/db/chap11/chap11.md
      - "Chapter 12: Concurrency Control": note/db/chap12/chap12.md
      - "Chapter 13: Recovery System": note/db/chap13/chap13.md
      - "资料下载：实验报告": note/db/file_download.md
    - 面向对象程序设计:
      - note/oop/index.md
      - "Chapter 1-2: Introduction": note/oop/chap1/chap1.md
      - "Chapter 3: STL": note/oop/chap3/chap3.md
      - "Chapter 4: Memory Model": note/oop/chap4/chap4.md
      - "Chapter 5: Class": note/oop/chap5/chap5.md
      - "Chapter 6: Composition, Inheritance & Polymorphism": note/oop/chap6/chap6.md
      - "Chapter 7: Copy Constructor": note/oop/chap7/chap7.md
      - "Chapter 8: Operator Overloading": note/oop/chap8/chap8.md
      - "Chapter 9: Streams": note/oop/chap9/chap9.md
      - "Chapter 10: Templates": note/oop/chap10/chap10.md
      - "Chapter 11: Iterators": note/oop/chap11/chap11.md
      - "Chapter 12: Exceptions": note/oop/chap12/chap12.md
      - "Chapter 13: Smart Pointers": note/oop/chap13/chap13.md
      - "Chapter 14: Miscellaneous Topics": note/oop/chap14/chap14.md
    - 离散数学:
      - note/dm/index.md
      - "Chapter 1: The Foundations—Logic and Proofs": note/dm/chap1/chap1.md
      - "Chapter 2: Basic Structures Sets, and Functions": note/dm/chap2/chap2.md
      - "Chapter 3: The Fundamentals Algorithms": note/dm/chap3/chap3.md
      - "Chapter 4: Induction and Recursion": note/dm/chap4/chap4.md
      - "Chapter 5: Counting": note/dm/chap5/chap5.md
      - "Chapter 6: Advanced Counting Techniques": note/dm/chap6/chap6.md
      - "Chapter 7: Relations": note/dm/chap7/chap7.md
      - "Chapter 8: Graphs": note/dm/chap8/chap8.md