site_name: 王浩雄的个人主页
site_url: https://note.haoxiong.wang
site_description: 王浩雄的个人主页
repo_name: "WangHX2024/note"
repo_url: https://github.com/WangHX2024/note
edit_uri: blob/master/docs
# copyright: Copyright &copy; 2023 - 2025 WangHX. <a href="https://beian.miit.gov.cn">冀ICP备2024085995号</a>
copyright: Copyright &copy; 2023 - 2025 WangHX.


theme:
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: 切换至夜间模式
      primary: "#448aff"
      accent: "#448aff"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
      primary: "#448aff"
      accent: "#448aff"
  font:
    text: LXGW WenKai Screen GB Screen
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    
extra:
  generator: true
  social:
    - icon: fontawesome/brands/weixin # 图标 : https://fontawesome.com
      link: /files/wechat.png
      name: 微信公众号
    - icon: fontawesome/brands/qq 
      link: https://3047901150.qzone.qq.com
      name: QQ空间
    - icon: fontawesome/brands/github 
      link: https://github.com/WangHX2024/
      name: GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/wanghx2025
      name: Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/wanghx01
      name: X
    - icon: fontawesome/solid/paper-plane
      link: mailto:<mail@haoxiong.wang>
      name: 电子邮件
  analytics:
    provider: google
    property: G-PLSZR8E9QE
    # feedback:
    #   title: 激励
    #   ratings:
    #     - icon: fontawesome/regular/hand-back-fist
    #       name: 激励
    #       data: 1
    #       note: >- 
    #         <center> 感谢支持</center>
            
extra_javascript:
  - css_js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - css_js/css.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  
plugins:
  - tags
  - blog:
      blog_dir: blog
      blog_toc: true
      draft: true
  - search
  - glightbox
  - statistics:
      page_check_metadata: counter
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      exclude:
  - git-committers:
      repository: wanghx2024/blog
      exclude:


markdown_extensions:
  - abbr
  - admonition
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - 主页 Home: 
    - index.md
    - 留言板: home/comment.md
    - 链接: home/link.md
  - 博客 Blog:
    - blog/index.md
  - 笔记 Note: 
    - note/index.md
    - 数字逻辑设计:
      - note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/数字逻辑设计 19b9c6b6155b806c8644e4a55f0b8dfb/index.md
      - "Chapter 1: Digital Systems and Information": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/数字逻辑设计 19b9c6b6155b806c8644e4a55f0b8dfb/Chapter 1 Digital Systems and Information 1a09c6b6155b80969c86c056c2730452.md
      - "Chapter 2: Combinational Logic Circuits": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/数字逻辑设计 19b9c6b6155b806c8644e4a55f0b8dfb/Chapter 2 Combinational Logic Circuits 1a99c6b6155b803c9ed5de06190f10f3.md
    - 计算机体系结构:
      - note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/计算机体系结构 19b9c6b6155b8024a072ca3bd97e46c8/index.md
      - "Chapter 1: Fundamentals of Computer Design": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/计算机体系结构 19b9c6b6155b8024a072ca3bd97e46c8/Chapter 1 Fundamentals of Computer Design 1a09c6b6155b807ab658ed3347e6259c.md
      - "Chapter 2: Memory Hierarchy Design": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/计算机体系结构 19b9c6b6155b8024a072ca3bd97e46c8/Chapter 2 Memory Hierarchy Design 1ad9c6b6155b807ead52ef8e7130e175.md
    - 数据库系统:
      - note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/数据库系统 19b9c6b6155b80d695c5ec0cf8168783/index.md
      - "Chapter 1: Introduction": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/数据库系统 19b9c6b6155b80d695c5ec0cf8168783/Chapter 1 Introduction 19d9c6b6155b803eb5f7c2fd986d31a6.md
      - "Chapter 2: Relational Model": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/数据库系统 19b9c6b6155b80d695c5ec0cf8168783/Chapter 2 Relational Model 19d9c6b6155b80bcae35c2f428878643.md
      - "Chapter 3: SQL": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/数据库系统 19b9c6b6155b80d695c5ec0cf8168783/Chapter 3 SQL 1a99c6b6155b80828260f17b18776fc1.md
    - 面向对象程序设计:
      - note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/面向对象程序设计 19b9c6b6155b80459f10d6623d7c42e7/index.md
      - "Lect 1-2: Introduction": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/面向对象程序设计 19b9c6b6155b80459f10d6623d7c42e7/Lect 1-2 Introduction 19d9c6b6155b8052bcc5cf56692c2e73.md
      - "Lect 3: STL": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/面向对象程序设计 19b9c6b6155b80459f10d6623d7c42e7/Lect 3 STL 1ae9c6b6155b80fcaac6c171fbde1937.md
    - 离散数学:
      - note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/离散数学 19b9c6b6155b80108585d9246eeefe70/index.md
      - "Chapter 1: The Foundations—Logic and Proofs": note/2024-2025 春夏课程笔记 19d9c6b6155b80e2bfcad2e0753bfbda/离散数学 19b9c6b6155b80108585d9246eeefe70/Chapter 1 The Foundations—Logic and Proofs 1a89c6b6155b8069b7a1d05e7af8f2ed.md

